server:
  port: 8083

spring:
  application:
    name: AurudaArticle #서비스 ID
  datasource:
    #url: jdbc:mysql://localhost:3306/auruda
    url: jdbc:mysql://mysql-container:3306/auruda
    username: crane
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect


logging:
  level:
    org.springframework.validation: DEBUG
    org.springframework.web.bind.annotation: DEBUG
    org:
      springframework:
        web: DEBUG
        validation: DEBUG
        web.bind.annotation: DEBUG
    hibernate:
      SQL: DEBUG
      type: TRACE

#eureka:
#  instance:
#    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka